# Generated by Django 3.1.4 on 2020-12-08 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('product_price', models.CharField(max_length=500)),
                ('product_info', models.TextField(max_length=1500)),
                ('search_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.search')),
            ],
        ),
    ]
